image: node:9.4.0
cache:
  paths:
    - node_modules/
    - .yarn
before_script:
  - apt-get update -qq && apt-get install
stages:
  - build
  - pages
  - production

Pages:
  stage: pages
  tags:
    - node
  script:
    - npm i -g apidoc
    - apidoc -i src/routes/api/Docs/ -o docs/
    - mv docs public
  artifacts:
    paths:
      - public
  only:
    - develop

Build:
  stage: build
  tags:
    - node
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install
  script:
    - npm run build

Deploy to Production:
  stage: production
  tags:
    - node
  before_script:
    # Generates to connect to the AWS unit the SSH key.
    - mkdir -p ~/.ssh
    - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    # Sets the permission to 600 to prevent a problem with AWS
    # that it's too unprotected.
    - chmod 600  ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - bash ./gitlab-deploy/.gitlab-deploy.prod.sh
  environment:
    name: production
    # Exposes a button that when clicked take you to the defined URL:
    url: http://ec2-13-59-173-91.us-east-2.compute.amazonaws.com:81
  when: manual
