pages:
  image: node:12

  cache:
    paths:
      - node_modules/

  script:
    - npm i -g apidoc
    - apidoc -i src/routes/api/Docs/ -o docs/
    - mv docs public

  artifacts:
    paths:
      - public

  only:
    - develop
